fail_fast: false
repos:
#  - repo: https://github.com/asottile/pyupgrade
#    rev: v3.15.0
#    hooks:
#      - id: pyupgrade
#        args:
#          - --keep-runtime-typing

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort


  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
        args:
          - --config=pyproject.toml

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        exclude: .*/__init__.py
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables


  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-check-blanket-noqa

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff
        args:
          - --config
          - ./pyproject.toml
          - --fix

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        types:
          - python
        args:
          - -c
          - pyproject.toml
        additional_dependencies:
          - toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic~=1.10.13


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: no-commit-to-branch
        args:
          - --branch
          - master


  - repo: local
    hooks:
      - id: poetry-lock
        name: poetry-lock
        description: run poetry install to install dependencies from the lock file
        entry: poetry lock
        args:
          - --no-update
        language: python
        pass_filenames: false
        files: pyproject.toml

      - id: poetry-install
        name: poetry-install
        description: run poetry install to install dependencies from the lock file
        entry: poetry install
        args:
          - --no-root
        language: python
        pass_filenames: false
        stages: [post-checkout, post-merge]
        always_run: true

      - id: poetry-export
        name: poetry-export
        entry: poetry export
        args:
          - -f
          - requirements.txt
          - -o requirements.txt
        language: python
        pass_filenames: false

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.10.0
    hooks:
      - id: pretty-format-yaml
        args:
          - --autofix
          - --offset
          - '2'
          - --indent
          - '2'
      - id: pretty-format-toml
        args: [--autofix]
        files: toml


#
#  - repo: https://github.com/python-poetry/poetry
#    rev: '1.3.0'
#    hooks:
#      - id: poetry-check
#      - id: poetry-lock
#      - id: poetry-export
